"""crear tablas iniciales

Revision ID: 4b286fb36892
Revises: 
Create Date: 2026-05-17 20:56:05.765378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b286fb36892'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('lectura', 'video', 'ejercicio', 'audio', 'juego', name='tipo_enum'), nullable=False),
    sa.Column('modalidad', sa.Enum('visual', 'auditivo', 'kinestesico', name='modalidad_enum'), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('condicion_objetivo', sa.String(), nullable=False),
    sa.Column('url_contenido', sa.String(), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('alumno', 'docente', 'padre', name='rol_enum'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('estudiantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('grado', sa.String(), nullable=False),
    sa.Column('condicion', sa.Enum('TEA', 'TDAH', 'Dislexia', 'Discalculia', 'Mixto', name='condicion_enum'), nullable=False),
    sa.Column('estilo_aprendizaje', sa.Enum('visual', 'auditivo', 'kinestesico', 'mixto', name='estilo_enum'), nullable=False),
    sa.Column('nivel_actual', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('riesgo_abandono', 'bajo_rendimiento', 'progreso_alto', name='alerta_enum'), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('vista', sa.Boolean(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_ml',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('prediccion', sa.JSON(), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesiones_aprendizaje',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('actividad_id', sa.UUID(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('tiempo_segundos', sa.Integer(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('aciertos', sa.Integer(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('puntuacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesiones_aprendizaje')
    op.drop_table('resultados_ml')
    op.drop_table('alertas')
    op.drop_table('estudiantes')
    op.drop_table('usuarios')
    op.drop_table('actividades')
    # ### end Alembic commands ###
