"""agregar status y created_by a usuarios

Revision ID: d205e4f90dd4
Revises: 962c87fd70e8
Create Date: 2026-05-29 00:39:04.422723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd205e4f90dd4'
down_revision: Union[str, Sequence[str], None] = '962c87fd70e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'users', ['assigned_by'], ['id'])
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'status')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'assigned_by')
    # ### end Alembic commands ###
